from __future__ import annotations

from typing import Any

from app.mf_client import mf_request


async def get_assistant() -> dict[str, Any]:
    """Get the current user's Personal Assistant config and context library."""
    return await mf_request("GET", "/api/ai-rep")


async def update_assistant(
    name: str,
    system_prompt: str = "",
    intro_message: str = "",
) -> dict[str, Any]:
    """Create or update the Personal Assistant for the current user."""
    return await mf_request(
        "POST",
        "/api/ai-rep",
        json_body={
            "name": name,
            "systemPrompt": system_prompt,
            "introMessage": intro_message,
        },
    )


async def deploy_assistant(meeting_id: str) -> dict[str, Any]:
    """Send the user's Personal Assistant into a meeting (on their behalf or alongside them)."""
    return await mf_request(
        "POST",
        "/api/ai-rep/deploy",
        json_body={"meetingId": meeting_id},
    )


async def add_assistant_context(title: str, content: str) -> dict[str, Any]:
    """Add a briefing note / context document to the Personal Assistant."""
    return await mf_request(
        "POST",
        "/api/ai-rep/context",
        json_body={"title": title, "content": content},
    )


async def list_debriefs() -> dict[str, Any]:
    """List post-meeting debriefs generated by the Personal Assistant."""
    return await mf_request("GET", "/api/debriefs")


async def get_debrief(debrief_id: str) -> dict[str, Any]:
    """Get a single debrief by id."""
    return await mf_request("GET", f"/api/debriefs/{debrief_id}")


async def get_user_settings() -> dict[str, Any]:
    """Get user settings including ringing preferences for AI-scheduled meetings."""
    return await mf_request("GET", "/api/user/settings")


async def update_ringing(ringing_enabled: bool) -> dict[str, Any]:
    """Enable or disable in-app ringing for AI-scheduled meetings.

    When off, the Assistant joins directly at the scheduled time instead of ringing first.
    """
    return await mf_request(
        "PATCH",
        "/api/user/settings",
        json_body={"ringingEnabled": ringing_enabled},
    )
